### ISSUE TITLE
Get error during Build 

### ISSUE THREAD

**Issue by faisalahmed** [timanrebel/Facebook#12]
i had used latest 2 release of your facebook module but receiving same error during build

error using  Ti SDK 3.5
[INFO] :   Invoking xcodebuild
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Project.build/Debug-iphoneos/Project-universal.build/Objects-normal/arm64/Project normal arm64
[ERROR] :  	Ld build/Project.build/Debug-iphoneos/Project-universal.build/Objects-normal/armv7/Project normal armv7
[ERROR] :  (2 failures)

and error using Ti SDK  3.4.1 & 3.4.0
[INFO] :   Invoking xcodebuild
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Debug-iphoneos/Project.app/Project normal armv7
[ERROR] :  (1 failure)

and i had also tested build from xcode 6.1.1 too and found that it is not able to find FaceBook Framework on it

**Comment by itsbrnrd** [comment]
Same here, couldn't find a workaround

**Comment by timanrebel** [comment]
Sorry guys, I screwed up I guess, could you try 1.0.11?

https://github.com/timanrebel/Facebook/releases/tag/1.0.11

**Comment by gurmukhp** [comment]
I get the same error with the latest build

[ERROR] :  *\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/TM-Meditation.build/Debug-iphoneos/TM-universal.build/Objects-normal/arm64/TM-normal arm64
[ERROR] :  (1 failure)
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/gurmukh/.appcelerator/install/4.0.0/package/node_modules/appc-cli-titanium/plugins/run.js:84:66)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
